version: '3.8'

services:
    php_fpm:
        build: ./docker/build/dev/php

    nginx:
        image: nginx:1.19.2-alpine

    mysql:
        image: mysql:8.0

    redis:
        image: redis:6.0.8-alpine
